name: CI Check

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  check_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      - name: Linting
        run: yarn lint
      
      - name: Transpile
        run: yarn compile
